import { DzogchenTerm } from './DzogchenTermsData';

// Additional 228 Dzogchen terms imported from Tibetan _Table_React1.ts
export const additionalTerms: Omit<DzogchenTerm, 'id'>[] = [
  { tibetanScript: 'སྙིང་རྗེ', wileyScript: 'snying rje', englishTransliteration: 'nyingje', englishTranslation: '1) compassion; mercy, pity, empathy, sympathy. 2) compassionate, affectionate; compassionate [one of nine moods of dance]' },
  { tibetanScript: 'སྙིང་རྗེ་སྐད', wileyScript: 'snying rje skad', englishTransliteration: 'nyingje kad', englishTranslation: 'lamentation, cry of compassion' },
  { tibetanScript: 'སྙིང་རྗེ་སགོམ་པ', wileyScript: 'snying rje sgom pa', englishTransliteration: 'nyingje gompa', englishTranslation: 'to cultivate compassion' },
  { tibetanScript: 'སྙིང་རྗེ་ཆེ་བ', wileyScript: 'snying rje che ba', englishTransliteration: 'nyingje chewa', englishTranslation: 'strong love for all life' },
  { tibetanScript: 'སྙིང་རྗེ་ཆེན་པོ', wileyScript: 'snying rje chen po', englishTransliteration: 'nyingje chenpo', englishTranslation: 'great compassion, name of avalokiteshvara' },
  { tibetanScript: 'སྙིང་རྗེ་ཚད་མེད', wileyScript: 'snying rje tshad med', englishTransliteration: 'nyingje chadmed', englishTranslation: 'immeasurable compassion' },
  { tibetanScript: '༄༄།།རིག་པ', wileyScript: 'rig pa', englishTransliteration: 'rigpa', englishTranslation: 'Rigpa. The state of awareness devoid of ignorance and dualistic fixation: (pure, sheer, instantaneous, instant) presence, know, knower, knowledge, understand, actually experience, (immediate, pure, intrinsic, aesthetic, value' },
  { tibetanScript: 'རིག་པ་ཀ་དག', wileyScript: 'rig pa ka dag', englishTransliteration: 'rigpa kadag', englishTranslation: 'primordial purity of rigpa' },
  { tibetanScript: 'རིག་པ་ཀུན་བཟང', wileyScript: 'rig pa kun bzang', englishTransliteration: 'rigpa kunzang', englishTranslation: 'Rigpa Samantabhadra' },
  { tibetanScript: 'རིག་པ་སྐད་ཅིག་མ', wileyScript: 'rig pa skad cig ma', englishTransliteration: 'rigpa kad chigma', englishTranslation: 'state of instant rigpa' },
  { tibetanScript: 'རིག་པ་ངོ་སྤྲོད', wileyScript: 'rig pa ngo sprod', englishTransliteration: 'rigpa ngochod', englishTranslation: 'direct introduction to intrinsic awareness' },
  { tibetanScript: 'རིག་པ་ངོ་སྤྲོད་གཅེར་མཐོང་རང་གྲོལ', wileyScript: 'rig pa ngo sprod gcer mthong rang grol', englishTransliteration: 'rigpa ngochod chertong rangdrol', englishTranslation: 'Self liberation through Awareness Seen in its Nakedness, from the Self liberated Wisdom Mind {zab chos zhi khro dgongs pa rang grol} revealed by Karma Lingpa. Self liberated Direct Seeing that Points Out the Awareness' },
  { tibetanScript: 'རིག་པ་གཅེར་མཐོང', wileyScript: 'rig pa gcer mthong', englishTransliteration: 'rigpa chertong', englishTranslation: 'seeing with naked awareness, naked recognition of pure awareness [JV]' },
  { tibetanScript: 'རིག་པ་གཅེར་བུ', wileyScript: 'rig pa gcer bu', englishTransliteration: 'rigpa cherbu', englishTranslation: 'naked Awareness' },
  { tibetanScript: 'རིག་པ་ཐོལ་སྐྱེས', wileyScript: 'rig pa thol skyes', englishTransliteration: 'rigpa thol kye', englishTranslation: 'the wisdom of realization suddenly/ spontaneously arising/ blossoming' },
  { tibetanScript: 'རིག་པ་རྡོ་རྗེའི་ལུ་གུ་རྒྱུད', wileyScript: 'rig pa rdo rje\'i lu gu rgyud', englishTransliteration: 'rigpa doje lugu gyud', englishTranslation: 'vajra chains of awareness' },
  { tibetanScript: 'རིག་པ་བྱང་ཆུབ་སེམས', wileyScript: 'rig pa byang chub sems', englishTransliteration: 'rigpa yang chub sem', englishTranslation: 'one\'s rigpa bodhicitta' },
  { tibetanScript: 'རིག་པ་ཚད་ཕེབས་ཀྱི་སྣང་བ', wileyScript: 'rig pa tshad phebs kyi snang ba', englishTransliteration: 'rigpa tshad pheb kyi nangwa', englishTranslation: 'the visionary appearance of reaching the limit of awareness, vision of awareness reaching fullness culminated Awareness' },
  { tibetanScript: 'རིག་པ་འཛིན་པ', wileyScript: 'rig pa \'dzin pa', englishTransliteration: 'rigpa dzinpa', englishTranslation: 'master/ holder of awareness/ one who has mastered (the recognition of) awareness/ upholds awareness/ awareness holder/ vidyadhara' },
  { tibetanScript: 'རིག་པ་རང་གྲོལ', wileyScript: 'rig pa rang grol', englishTransliteration: 'rigpa rangdrol', englishTranslation: 'the natural liberation of awareness' },
  { tibetanScript: 'རིག་པ་རང་གྲོལ་གྱི་རྒྱུད', wileyScript: 'rig pa rang grol gyi rgyud', englishTransliteration: 'rigpa rangdrol gyi gyud', englishTranslation: 'Tantra of Self liberated Awareness. This scripture teaches how awareness is uncreated but is liberated by itself, how to control appearances, to grow familiar with the vajra chain, and to naturally free all of samsara and nirvana' },
  { tibetanScript: 'རིག་པ་རང་ངོ་སྤྲད་པ', wileyScript: 'rig pa rang ngo sprad pa', englishTransliteration: 'rigpa rang ngo chadpa', englishTranslation: 'introducing the awareness of one\'s own nature' },
  { tibetanScript: 'རིག་པའི་ཀློང', wileyScript: 'rig pa\'i klong', englishTransliteration: 'rigpai long', englishTranslation: 'expanse/ space of insight = sugatagarbha' },
  { tibetanScript: 'རིག་པའི་ཁུ་བྱུག', wileyScript: 'rig pa\'i khu byug', englishTransliteration: 'rigpai khu yug', englishTranslation: 'the cuckoo of Awareness; \"the cuckoo\'s cry of awareness,\" by Vairochana' },
  { tibetanScript: 'རིག་པའི་རྒྱལ་པོ', wileyScript: 'rig pa\'i rgyal po', englishTransliteration: 'rigpai gyalpo', englishTranslation: 'majestic awareness, prince of learning, science, supreme rigpa, a wrathful king' },
  { tibetanScript: 'རིག་པའི་མེ་ཏོག', wileyScript: 'rig pa\'i me tog', englishTransliteration: 'rigpai metog', englishTranslation: 'flower of awareness. To toss the \'flower of awareness\' means to throw away the fixation on good and bad as to the dualistic experience of self visualization and front visualization, samaya being and wisdom being' },
  { tibetanScript: 'རིག་པའི་རང་རྩལ', wileyScript: 'rig pa\'i rtsal', englishTransliteration: 'rigpai tsal', englishTranslation: 'potency of pure presence, power of awareness, manifestive power/expression of awareness, functioning energy of awareness' },
  { tibetanScript: 'རིག་པའི་རང་ངོ', wileyScript: 'rig pa\'i rang ngo', englishTransliteration: 'rigpai rangngo', englishTranslation: 'the natural face of awareness' },
  { tibetanScript: 'རིག་པའི་རང་མདངས', wileyScript: 'rig pa\'i rang mdangs', englishTransliteration: 'rigpai rangdang', englishTranslation: 'the natural radiance of mind' },
  { tibetanScript: 'རིག་པའི་རང་རྩལ', wileyScript: 'rig pa\'i rang rtsal', englishTransliteration: 'rigpai rangtsal', englishTranslation: 'the play of the mind, natural expression of awareness' },
  { tibetanScript: 'རིག་པའི་རང་ཟེར', wileyScript: 'rig pa\'i rang zer', englishTransliteration: 'rigpai rangzer', englishTranslation: 'inherent self rays of awareness' },
  { tibetanScript: 'རིག་པའི་རང་འོད', wileyScript: 'rig pa\'i rang \'od', englishTransliteration: 'rigpai rang od', englishTranslation: 'inherent self light of awareness' },
  { tibetanScript: 'རིག་པའི་རལ་གྲི', wileyScript: 'rig pa\'i ral gri', englishTransliteration: 'rigpai ralgri', englishTranslation: 'sword of awareness' },
  { tibetanScript: 'རིག་པའི་རླུང', wileyScript: 'rig pa\'i rlung', englishTransliteration: 'rigpai lung', englishTranslation: 'wind of awareness' },
  { tibetanScript: 'རིག་པའི་གཤིས', wileyScript: 'rig pa\'i gshis', englishTransliteration: 'rigpai shi', englishTranslation: 'state of rigpa' },
  { tibetanScript: 'རིག་པས་རིག་པ་གྲོལ་བ', wileyScript: 'rig pas rig pa grol ba', englishTransliteration: 'rigpai rigpa drolba', englishTranslation: 'awareness is liberated by awareness' },
  { tibetanScript: 'ཡེ་ཤེས', wileyScript: 'ye shes', englishTransliteration: 'yeshe', englishTranslation: 'jnana, (exalted, primordial) wisdom, (primal, transcending, original, unitary, authentic, pure, absolute, a priori, genuine, spiritual, ever fresh, pristine) awareness' },
  { tibetanScript: 'ཡེ་ཤེས་ཀྱི་དཀྱིལ་འཁོར', wileyScript: 'ye shes kyi dkyil \'khor', englishTransliteration: 'yeshe kyi kyilkhor', englishTranslation: 'the wisdom mandala' },
  { tibetanScript: 'ཡེ་ཤེས་ཀྱོ་མཀའ་འགྲོ', wileyScript: 'ye shes kyi mka\' \'gro', englishTransliteration: 'yeshe kyi kadro', englishTranslation: 'wisdom dakini' },
  { tibetanScript: 'ཡེ་ཤེས་ཀྱི་སྐུ', wileyScript: 'ye shes kyi sku', englishTransliteration: 'yeshe kyi ku', englishTranslation: 'wisdom form' },
  { tibetanScript: 'ཡེ་ཤེས་ཀྱི་ཐིག་ལེ', wileyScript: 'ye shes kyi thig le', englishTransliteration: 'yeshe kyi thigle', englishTranslation: 'wisdom bindu' },
  { tibetanScript: 'ཡེ་ཤེས་ཀྱི་སྡོམ་པ', wileyScript: 'ye shes kyi sdom pa', englishTransliteration: 'yeshe kyi dompa', englishTranslation: 'the wisdom which binds together (Wisdom Vow [MTC])' },
  { tibetanScript: 'ཡེ་ཤེས་ཀྱི་ཕྱག་རྒྱ', wileyScript: 'ye shes kyi phyag rgya', englishTransliteration: 'yeshe kyi chaggya', englishTranslation: 'jnanamudra, wisdom mudra, visualized consort, awareness' },
  { tibetanScript: 'ཡེ་ཤེས་ཀྱི་ཕྱག་རྒྱང་མ', wileyScript: 'ye shes kyi phyag rgya ma', englishTransliteration: 'yeshe kyi chag gyama', englishTranslation: 'wisdom seal [a meditated consort in tantra]' },
  { tibetanScript: 'ཡེ་ཤེས་ཀྱི་འོད་སྐུ', wileyScript: 'ye shes kyi \'od sku', englishTransliteration: 'yeshe kyi odku', englishTranslation: 'the wisdom body of light' },
  { tibetanScript: 'ཡེ་ཤེས་ཀྱི་རོལ་པ', wileyScript: 'ye shes kyi rol pa', englishTransliteration: 'yeshe kyi rolpa', englishTranslation: 'wisdom energy' },
  { tibetanScript: 'ཡེ་ཤེས་ཀྱི་རླུང', wileyScript: 'ye shes kyi rlung', englishTransliteration: 'yeshe kyi lung', englishTranslation: 'wisdom winds/prana' },
  { tibetanScript: 'ཡེ་ཤེས་སྐར་མདའི་ཕྱག', wileyScript: 'ye shes skar mda\'i phyag', englishTransliteration: 'yeshe kar dai chag', englishTranslation: 'wisdom shooting star mudra' },
  { tibetanScript: 'ཡེ་ཤེས་སྒྱུ་འཕྲུལ་གྲྭ་བའི་རོལ་གར', wileyScript: 'ye shes sgyu \'phrul grwa ba\'i rol gar', englishTransliteration: 'yeshe gyutrul grawai rol gar', englishTranslation: 'manifestation of the magical net of wisdom' },
  { tibetanScript: 'ཡེ་ཤེས་ང', wileyScript: 'ye shes nga', englishTransliteration: 'yeshe nga', englishTranslation: 'the five wisdoms' },
  { tibetanScript: 'ཡེ་ཤེས་ཆེན་པོ', wileyScript: 'ye shes chen po', englishTransliteration: 'yeshe chenpo', englishTranslation: 'great wisdom' },
  { tibetanScript: 'ཡེ་ཤེས་ཆོས་སྐུ', wileyScript: 'ye shes chos sku', englishTransliteration: 'yeshe choku', englishTranslation: 'wisdom dharmakaya: wisdom truth body, body of wisdom qualities' },
  { tibetanScript: 'ཡེ་ཤེས་འཆོལ་བ', wileyScript: 'ye shes \'chol ba', englishTransliteration: 'yeshe cholba', englishTranslation: 'crazy wisdom' },
  { tibetanScript: 'ཡེ་ཤེས་བརྗོད་བྲལ', wileyScript: 'ye shes brjod bral', englishTransliteration: 'yeshe joddral', englishTranslation: 'an inexpressible primal awareness' },
  { tibetanScript: 'ཡེ་ཤེས་ཉམས་འབར', wileyScript: 'ye shes nyams \'bar', englishTransliteration: 'yeshe nyambar', englishTranslation: 'ablaze with wisdom experience' },
  { tibetanScript: 'ཡེ་ཤེས་སྙྱིང་པོ', wileyScript: 'ye shes snying po', englishTransliteration: 'yeshe nyingpo', englishTranslation: '(the heart of wisdom, wisdom essence [MTC])' },
  { tibetanScript: 'ཡེ་ཤེས་ཐོགས་པ་མེད་པ', wileyScript: 'ye shes thogs pa med pa', englishTransliteration: 'yeshe togpa medpa', englishTranslation: 'unobstructed wisdom' },
  { tibetanScript: 'ཡེ་ཤེས་དག་པ', wileyScript: 'ye shes dag pa', englishTransliteration: 'yeshe dagpa', englishTranslation: 'pure wisdom' },
  { tibetanScript: 'ལྷུན་གྲུབ', wileyScript: 'lhun grub', englishTransliteration: 'lhundrup', englishTranslation: '1) spontaneous presence, One of the two main aspects of Dzogchen teaching, the other being \'primordial purity\' (ka dag). 2) effortless/ spontaneous fulfillment; spontaneously self perfected; effortless, spontaneously perfect / accomplished, spontaneously self existing, spontaneous, wishfulfilling' },
  { tibetanScript: 'ལྷུན་གྲུབ་ཀ་དག', wileyScript: 'lhun grub ka dag', englishTransliteration: 'lhundrup kadag', englishTranslation: 'spontaneous presence and primordial purity' },
  { tibetanScript: 'ལྷུན་གྲུབ་ཀྱི་ཀློང', wileyScript: 'lhun grub kyi klong', englishTransliteration: 'lhundrup kyi long', englishTranslation: 'the space of spontaneous presence' },
  { tibetanScript: 'ལྷུན་གྲུབ་ཀྱི་དཀྱིལ་འཁོར་གསུམ', wileyScript: 'lhun grub kyi dkyil \'khor gsum', englishTransliteration: 'lhundrup kyi kyilkhor sum', englishTranslation: 'the three spontaneously present mandalas' },
  { tibetanScript: 'ལྷུན་གྲུབ་ཀྱི་འཆར་སྒོ་བརྒྱད', wileyScript: 'lhun grub kyi \'char sgo brgyad', englishTransliteration: 'lhundrup kyi chargo gyad', englishTranslation: 'eight avenues for the arising of spontaneous presence' },
  { tibetanScript: 'ལྷུན་གྲུབ་ཀྱི་འཆར་སྒོ་བརྒྱད་སུ་ཡལ་ནས', wileyScript: 'lhun grub kyi \'char sgo dbyings su yal nas', englishTransliteration: 'lhundrup kyi chargo gyad su yalnai', englishTranslation: 'when the visions of luminosity have subsided into space' },
  { tibetanScript: 'ལྷུན་སྒྲུབ་ཀྱི་གནས་ལུགས', wileyScript: 'lhun grub kyi gnas lugs', englishTransliteration: 'lhundrup kyi nai lug', englishTranslation: 'the spontaneously present natural state' },
  { tibetanScript: 'ལྷུན་གྲུབ་ཀྱི་སནང་བ', wileyScript: 'lhun grub kyi snang ba', englishTransliteration: 'lhundrup kyi nangwa', englishTranslation: 'experiences of spontaneous presence, spontaneously present manifestations' },
  { tibetanScript: 'ལྷུན་གྲུབ་ཀྱི་གཟུགས་སྐུ', wileyScript: 'lhun grub kyi gzugs sku', englishTransliteration: 'lhundrup kyi zugku', englishTranslation: 'Rupakaya of spontaneous presence. The display of the bardo of dharmata' },
  { tibetanScript: 'ལྷུན་གྲུབ་ངང', wileyScript: 'lhun grub ngang', englishTransliteration: 'lhundrup ngang', englishTranslation: 'state of self perfection' },
  { tibetanScript: 'ལྷུན་གྲུབ་ཆེན་པོ', wileyScript: 'lhun grub chen po', englishTransliteration: 'lhundrup chenpo', englishTranslation: 'the great spontaneous presence' },
  { tibetanScript: 'ལྷུན་གྲུབ་ཏུ་རྫོགས་པ', wileyScript: 'lhun grub tu rdzogs pa', englishTransliteration: 'lhundrup tu dzogpa', englishTranslation: 'spontaneously complete/ perfect spontaneous presence of perfection' },
  { tibetanScript: 'ལྷུན་གྲུབ་སྟུག་པོ་བཀོད་པ', wileyScript: 'lhun grub stug po bkod pa', englishTransliteration: 'lhundrup tugpo kodpa', englishTranslation: 'the dense array of spontaneous presence' },
  { tibetanScript: 'ལྷུན་གྲུབ་ཐོད་རྒལཇ', wileyScript: 'lhun grub thod rgal', englishTransliteration: 'lhundrup togal', englishTranslation: 'Direct Crossing of spontaneous presence; spontaneously accomplished Tögal practice, spontaneously present Tögal, all surpassing realization of spontaneous presence' },
  { tibetanScript: 'ལྷུན་གྲུབ་དབྱིངས', wileyScript: 'lhun grub dbyings', englishTransliteration: 'lhundrup ying', englishTranslation: 'spontaneous presence as basic space' },
  { tibetanScript: 'ཀ་དག', wileyScript: 'ka dag', englishTransliteration: 'kadag', englishTranslation: 'pure from the beginning, initially pure, transcendence, purely transcendent, primordially pure, primordial purity, original purity, inherent purity, original purity, original purity, primordially empty' },
  { tibetanScript: 'ཀ་དག', wileyScript: 'ka dag klong', englishTransliteration: 'kadag long', englishTranslation: 'space/ expanse of primordial purity' },
  { tibetanScript: 'ཀ་དག་ཀློང', wileyScript: 'ka dag klong yangs', englishTransliteration: 'kadag long yang', englishTranslation: 'the vast space of primordial purity' },
  { tibetanScript: 'ཀ་དག་ཁྲེགས་ཆོད', wileyScript: 'ka dag khregs chod', englishTransliteration: 'kadag treng chod', englishTranslation: '1) Cutting Through of primordial purity. 2) cutting through resistance to primordial purity' },
  { tibetanScript: 'ཀ་དག་ཁྲེངས་ཆོད་ཀྱི་དཁོངས་པ', wileyScript: 'ka dag khregs chod kyi dgongs pa', englishTransliteration: 'kadag treng chod kyi gongpa', englishTranslation: 'Trekchö realization of primordial purity' },
  { tibetanScript: 'ཀ་དག་ཁྲེངས་ཆོད་ཀྱི་དཁོངས་པ་མ་ནོར་བ་རྒྱུད་ལ་སྐྱུད་ཏེ', wileyScript: 'ka dag khregs chod kyi dgongs pa ma nor ba rgyud la skyes te', englishTransliteration: 'kadag treng chod kyi gongpama norba gyud la kye te', englishTranslation: 'experienced realization of the primordial purity of Trekcho without error' },
  { tibetanScript: 'ཀ་དག་གི་ཀློང', wileyScript: 'ka dag gi klong', englishTransliteration: 'kadag gi long', englishTranslation: 'primordially pure space, space of primordial purity, primordially pure expanse, within primordial purity' },
  { tibetanScript: 'ཀ་དག་གྲོལ་ས', wileyScript: 'ka dag gi grol sa', englishTransliteration: 'kadag gi drol sa', englishTranslation: 'the liberation place of primordial purity' },
  { tibetanScript: 'ཀ་དག་གི་ངོ་བོ', wileyScript: 'ka dag gi ngo bo', englishTransliteration: 'kadag gi ngobo', englishTranslation: 'essence of primordial purity' },
  { tibetanScript: 'ཀ་དག་གི་ཆོས་སཀུ', wileyScript: 'ka dag gi chos sku', englishTransliteration: 'kadag gi choku', englishTranslation: 'the primordially pure dharmakaya.(essence of primordially pure body of basic space[MTC])' },
  { tibetanScript: 'ཀ་དག་གི་གནས་ལུགས', wileyScript: 'ka dag gi gnas lugs', englishTransliteration: 'kadag gi nai lug', englishTranslation: 'the natural condition of primordial purity, the primordial purity of things as they are' },
  { tibetanScript: 'ཀ་དག་གི་སྤྱི་གཞི', wileyScript: 'ka dag gi spyi gzhi', englishTransliteration: 'kadag gi chishi', englishTranslation: 'common ground of primordial purity' },
  { tibetanScript: 'ཀ་དག་གི་ཡེ་གཞི', wileyScript: 'ka dag gi ye gzhi', englishTransliteration: 'kadag gi yeshi', englishTranslation: 'original ground of primordial purity' },
  { tibetanScript: 'ཀ་དག་གི་རིག་པ', wileyScript: 'ka dag gi rig pa', englishTransliteration: 'kadag gi rigpa', englishTranslation: 'primordially pure awareness, primordial purity of insight' },
  { tibetanScript: 'ཀ་དག་གི་ལམ', wileyScript: 'ka dag gi lam', englishTransliteration: 'kadag gi lam', englishTranslation: 'the path of primordial purity' },
  { tibetanScript: 'ཀ་དག་ཅིག་སྟོང', wileyScript: 'ka dag cig stong', englishTransliteration: 'kadag chig tong', englishTranslation: 'the awareness and emptiness of primal purity' },
  { tibetanScript: 'ཀ་དག་ཆེན་པོ', wileyScript: 'ka dag chen po', englishTransliteration: 'kadag chenpo', englishTranslation: 'pure absoluteness, great primordial purity, state of total primordial purity' },
  { tibetanScript: 'ཀ་དག་ཆོས་ཀྱི་སྐུ', wileyScript: 'ka dag chos kyi sku', englishTransliteration: 'kadag cho kyi ku', englishTranslation: '1) primordially pure dharmakaya. 2) dharmakaya of primordial purity' },
  { tibetanScript: 'ཀ་དག་ཆོས་སྐུའི་སྣང་བ', wileyScript: 'ka dag chos sku\'i snang ba', englishTransliteration: 'kadag choku nangwa', englishTranslation: 'the dharmakaya manifestation of primordial purity' },
  { tibetanScript: 'ཀ་དག་ཆོས་སྐུའི་བར་དོ', wileyScript: 'ka dag chos sku\'i bar do', englishTransliteration: 'kadag choku bardo', englishTranslation: 'the bardo of primordially pure dharmakaya' },
  { tibetanScript: 'ཀ་དག་ཆོས་སྐུའི་འོད་གསལ', wileyScript: 'ka dag chos sku\'i \'od gsal', englishTransliteration: 'kadag choku odsal', englishTranslation: 'dharmakaya luminosity of primordial purity' },
  { tibetanScript: 'ཀ་དག་ཆོས་སྐུའི་རང་གདངས', wileyScript: 'ka dag chos sku\'i rang gdangs', englishTransliteration: 'kadag choku rangdang', englishTranslation: 'the self manifestation of primordially pure dharmakaya' },
  { tibetanScript: 'ཀ་དག་ཆོས་སྐུའི་རིག་པ', wileyScript: 'ka dag chos sku\'i rig pa', englishTransliteration: 'kadag choku rigpa', englishTranslation: 'primordially pure dharmakaya awareness' },
  { tibetanScript: 'ཀ་དག་ཆོས་ཟད', wileyScript: 'ka dag chos zad', englishTransliteration: 'kadag cho zad', englishTranslation: 'the primordially pure exhaustion of phenomena' },
  { tibetanScript: 'ཀ་དག་ཆོས་ཟད་བློ་འདས་ཆེན་པོ', wileyScript: 'ka dag chos zad blo \'das chen po', englishTransliteration: 'kadag cho zad lo da chenpo', englishTranslation: '1) great primordial purity beyond concepts in which phenomena has been exhausted. 2) exhaustion of phenomena beyond concepts' },
  { tibetanScript: 'ཀ་དག་གཏིང་གསལ་ཆོས་ཀྱི་སྐུ', wileyScript: 'ka dag gting gsal chos kyi sku', englishTransliteration: 'kadag tingsal chokyi ku', englishTranslation: 'the primordially pure dharmakaya of basic clarity, dharmakaya the fundamentally luminous primordial purity' },
  { tibetanScript: 'ཀ་དག་སཏོང་པ་ཉིད', wileyScript: 'ka dag stong pa nyid', englishTransliteration: 'kadag tongpa nyid', englishTranslation: 'primordially pure emptiness' },
  { tibetanScript: 'ཀ་དག་སཏོང་གསལ་ཆོས་ཀྱི་སྐུ', wileyScript: 'ka dag stong gsal chos sku', englishTransliteration: 'kadag tongsal choku', englishTranslation: 'primordially pure dharmakaya of empty cognizance, primordial purity of empty luminous dharmakaya' },
  { tibetanScript: 'ཀ་དག་གདོད་མའི་གཤིས', wileyScript: 'ka dag gdod ma\'i gshis lugs', englishTransliteration: 'kadag dodmai shilug', englishTranslation: 'original nature of primordial purity' },
  { tibetanScript: 'ཀ་དག་རྣལ་འབྱོར', wileyScript: 'ka dag rnal \'byor', englishTransliteration: 'kadag naljor', englishTranslation: 'practitioners who have acquired authentic knowledge of the original purity' },
  { tibetanScript: 'ཀ་དག་དབྱིངས་སུ་བསྒྲལ', wileyScript: 'ka dag dbyings su bsgral', englishTransliteration: 'kadag ying su dral', englishTranslation: 'liberated into primordially pure space' },
  { tibetanScript: 'ཀ་དག་གཟིའི་གངས་ལུགས', wileyScript: 'ka dag gzhi\'i gnas lugs', englishTransliteration: 'kadagshi nai lug', englishTranslation: 'the natural condition of the primordial pure ground, primordial purity the way things fundamentally are' },
  { tibetanScript: 'ཀ་དག་ཟང་ཐལ་ངང', wileyScript: 'ka dag zang thal ngang', englishTransliteration: 'kadag zang thal ngang', englishTranslation: 'unimpeded state of primordial purity' },
  { tibetanScript: 'ཀ་དག་ཡེ་ཐོག་ཏུ་གྲོལ་བ', wileyScript: 'ka dag ye thog tu grol ba', englishTransliteration: 'kadag yethog tu drolba', englishTranslation: 'to be liberated into the original primordial purity' },
  { tibetanScript: 'ཀ་དག་ཡེ་གཞི', wileyScript: 'ka dag ye gzhi', englishTransliteration: 'kadag yeshi', englishTranslation: 'original ground of primordial purity' },
  { tibetanScript: 'ཀ་དག་རང་ངོ་འཕྲོད་པ', wileyScript: 'ka dag rang ngo \'phrod pa', englishTransliteration: 'kadag rang ngo trodpa', englishTranslation: 'recognizing one\'s nature as primordial purity' },
  { tibetanScript: 'ཀ་དག་རིག་སྟོང', wileyScript: 'ka dag rang rig', englishTransliteration: 'kadag rangrig', englishTranslation: 'primordially pure self awareness' },
  { tibetanScript: 'ཀ་དག་རིག་སྟོང', wileyScript: 'ka dag rig stong', englishTransliteration: 'kadag rigtong', englishTranslation: 'awareness and emptiness of primordial purity' },
  { tibetanScript: 'ཀ་དག་རིག་སྟོང་མཚོན་པ', wileyScript: 'ka dag rig stong mtshon pa', englishTransliteration: 'kadag rig tong tsonpa', englishTranslation: 'symbolize the awareness and emptiness of primal purity' },
  { tibetanScript: 'ཀ་དག་རིག་པ་ཤེས་རབ་རང་བྱུང་གི་སྒྲོན་མ', wileyScript: 'ka dag rig pa shes rab rang byung gi sgron ma', englishTransliteration: 'kadag rigpa sherab rangjung gi dronma', englishTranslation: 'the lamp of self originated discriminating wisdom which is primordially pure awareness' },
  { tibetanScript: 'ཀ་དག་ལྷན་སྐྱེས', wileyScript: 'ka dag lhan skyes', englishTransliteration: 'kadag lhan kye', englishTranslation: '1) innately pure from the beginning, innate primordial purity' },
  { tibetanScript: 'ཀ་དག་ལྷུན་གྲུབ', wileyScript: 'ka dag lhun grub', englishTransliteration: 'kadag lhundrup', englishTranslation: 'primordial purity and spontaneous presence, original purity & self perfection, primordially pure & self perfected' },
  { tibetanScript: 'འོད', wileyScript: '\'od', englishTransliteration: 'od', englishTranslation: 'radiance, light, splendor, luminosity, shine, brilliance, brightness, radiancy' },
  { tibetanScript: 'འོད་ཀོར', wileyScript: '\'od kor', englishTransliteration: 'od kor', englishTranslation: 'lantern, luminous circle' },
  { tibetanScript: 'འོད་ཀྱི་སཀུ', wileyScript: '\'od kyi sku', englishTransliteration: 'od kyi ku', englishTranslation: 'luminosity body, Body of Light' },
  { tibetanScript: 'འོད་ཀྱི་སཀུ་འགྲུབ', wileyScript: '\'od kyi skur \'grub', englishTransliteration: 'od kyi kur drub', englishTranslation: 'dissolve in the Body of Light' },
  { tibetanScript: 'འོད་ཀྱི་གོང་བུ', wileyScript: '\'od kyi gong bu', englishTransliteration: 'od kyi gong bu', englishTranslation: 'luminous spheres' },
  { tibetanScript: 'འོད་ཀྱི་སྙིང་པོ', wileyScript: '\'od kyi snying po', englishTransliteration: 'od kyi nyingpo', englishTranslation: 'essence of light' },
  { tibetanScript: 'འོད་ཀྱི་སྣང་བ', wileyScript: '\'od kyi snang ba', englishTransliteration: 'od kyi nangwa', englishTranslation: 'luminous vision/ manifestation' },
  { tibetanScript: 'འོད་ཀྱི་ཇེར་ཐག', wileyScript: '\'od kyi zer thag', englishTransliteration: 'od kyi zerthag', englishTranslation: 'rays of light' },
  { tibetanScript: 'འོད་ཀྱི་སྣང་བ', wileyScript: '\'od kyi snang ba', englishTransliteration: 'od kyi nangwa', englishTranslation: 'luminous vision/ manifestation' },
  { tibetanScript: 'འོད་ཀྱི་ལུས', wileyScript: '\'od kyi lus', englishTransliteration: 'od kyi lu', englishTranslation: 'Body of light. The body of light of the five wisdoms. It\'s devoid of materiality' },
  { tibetanScript: 'འོད་སཀུ', wileyScript: '\'od sku', englishTransliteration: 'od ku', englishTranslation: 'his body made of light; body of light' },
  { tibetanScript: 'འོད་སྐུར་གྲོལ', wileyScript: '\'od skur grol', englishTransliteration: 'od kur drol', englishTranslation: 'become liberated in the body of light' },
  { tibetanScript: 'འོད་ཁྱིམ', wileyScript: '\'od khyim', englishTransliteration: 'od khyim', englishTranslation: 'light spheres, dome of light' },
  { tibetanScript: 'འོད་ཁྱུག་ཁྱུག', wileyScript: '\'od khyug khyug', englishTransliteration: 'od khyug khyug', englishTranslation: 'sparkling w light, glittering, twinkling, sparkling, [cord like] light going hither and thither' },
  { tibetanScript: 'འོད་གྱུགས', wileyScript: '\'od khyugs', englishTransliteration: 'od khyugs', englishTranslation: 'shimmering light' },
  { tibetanScript: 'འོད་ལྔ་པ', wileyScript: '\'od lnga pa', englishTransliteration: 'od ngapa', englishTranslation: 'rainbow' },
  { tibetanScript: 'འོད་ཅན', wileyScript: '\'od can', englishTransliteration: 'od can', englishTranslation: '1) brilliant, radiant; 2) Venus; 3) star; 4) firefly' },
  { tibetanScript: 'འོད་ཐིག', wileyScript: '\'od thig', englishTransliteration: 'od thig', englishTranslation: 'light drop, sphere of light' },
  { tibetanScript: 'རང་བྱུང', wileyScript: 'rang byung', englishTransliteration: 'rangjung', englishTranslation: '1) naturally occuring w/o work; 2) dhrmadhatu, chos kyi dbyings; 3) (met) Bhrama [rang byung khams las \'das pa natural, self existing' },
  { tibetanScript: 'རང་བྱུང་དཀྱིལ་འཁོར་ལྷ', wileyScript: 'rang byung dkyil \'khor lha', englishTransliteration: 'rangjung kyil khor lha', englishTranslation: 'the self existing mandala deities' },
  { tibetanScript: 'རང་བྱུང་གི་ཆ་རྐྱེན', wileyScript: 'rang byung gi cha rkyen', englishTransliteration: 'rangjung gi cha rkyen', englishTranslation: 'natural condition' },
  { tibetanScript: 'རང་བྱུང་གི་རྟོགས་པ་རྒྱུད་ལ་སྐྱེས', wileyScript: 'rang byung gi rtogs pa rgyud la skyes', englishTransliteration: 'rangjung gi rtogspa gyud la kye', englishTranslation: 'spontaneous realization was born within me' },
  { tibetanScript: 'རང་བྱུང་གི་འོད་གསལ', wileyScript: 'rang byung gi \'od gsal', englishTransliteration: 'rangjung gi odsal', englishTranslation: 'self existing luminosity' },
  { tibetanScript: 'རང་བྱུང་གི་ཡེ་ཤེས', wileyScript: 'rang byung gi ye shes', englishTransliteration: 'rangjung gi yeshe', englishTranslation: 'self existing wakefulness. Self originated primordial wisdom, self existing basic intelligence, natural wisdom' },
  { tibetanScript: 'རང་བྱུང་གི་སེམས་ཀྱི་ངོ་བོ', wileyScript: 'rang byung gi sems kyi ngo bo', englishTransliteration: 'rangjung gi sem kyi ngobo', englishTranslation: 'the essence of the self arising mind' },
  { tibetanScript: 'རང་བྱུང་གི་སེམས་ཀྱི་ནོ་བོ', wileyScript: 'rang byung gi sems kyi no bo', englishTransliteration: 'rangjung gi sem kyi nobo', englishTranslation: 'the essence of the self arising mind' },
  { tibetanScript: 'རང་བྱུང་ཆེན་པོ', wileyScript: 'rang byung chen po', englishTransliteration: 'rangjung chenpo', englishTranslation: 'supreme naturally/ self occurring nature' },
  { tibetanScript: 'རང་བྱུང་ཐུགས་རྗེ', wileyScript: 'rang byung thugs rje', englishTransliteration: 'rangjung thugsje', englishTranslation: 'natural compassion' },
  { tibetanScript: 'རང་བྱུང་ཡེ་ཤེས', wileyScript: 'rang byung ye shes', englishTransliteration: 'rangjung yeshe', englishTranslation: 'Self existing wakefulness. Basic wakefulness that is independent of intellectual constructs. Self existing wisdom, self originated knowledge, self originated primal awareness; self refreshing awareness, self generating pristine awareness; self' },
  { tibetanScript: 'རང་བྱུང་ཡེ་ཤེས་ཀྱི་སྐུ', wileyScript: 'rang byung ye shes kyi sku', englishTransliteration: 'rangjung yeshe kyiku', englishTranslation: 'the form of self existing wakefulness' },
  { tibetanScript: 'རང་བྱུང་ཡེ་ཤེས་ཀྱི་རླུང', wileyScript: 'rang byung ye shes kyi rlung', englishTransliteration: 'rangjung yeshe kyi lung', englishTranslation: 'wind of self existing wisdom' },
  { tibetanScript: 'རང་བྱུང་ཡེ་ཤེས་གི་ཐུགས', wileyScript: 'rang byung ye shes gi thugs', englishTransliteration: 'rangjung yeshe gi thugs', englishTranslation: 'the mind of intrinsic wisdom' },
  { tibetanScript: 'སྣང', wileyScript: 'snang', englishTransliteration: 'nang', englishTranslation: 'appear[ance], phenomena, presence, show, be seen, be visible, manifest[ations], seem, day light, illumination, thought, heart, [be on 1\'s] mind, see, perception, experience, illuminate, make visible, 1\'s outlook, lighten, occur, projections, feeling for, inclination to' },
  { tibetanScript: 'སྣང་བའི་ཡུལ', wileyScript: 'snang b\'I yul', englishTransliteration: 'nang b\'I yul', englishTranslation: '[objects of] appearance; apparent object' },
  { tibetanScript: 'སྣང་རྐྱེན', wileyScript: 'snang rkyen', englishTransliteration: 'nang rkyen', englishTranslation: 'conditions accounting for the manifestation of apparent phenomena' },
  { tibetanScript: 'སྣང་བཅས་རྣལ་འབྱོར་མངོན་སུམ', wileyScript: 'snang bcas rnal \'byor mngon sum', englishTransliteration: 'nang bcas nal jor mngon sum', englishTranslation: 'direct yogic perception with appearance' },
  { tibetanScript: 'སྣང་ཇི་སྙེད་ཀུན', wileyScript: 'snang ji snyed kun', englishTransliteration: 'nang ji snyedkun', englishTranslation: 'all appearances whatever exist (in this world)' },
  { tibetanScript: 'སྣང་ཉམས', wileyScript: 'snang nyams', englishTransliteration: 'nang nyam', englishTranslation: 'visionary experience; visions and experiences; vision, experience, visionary experience, visions and experiences, abbr. of {snang ba dang nyams gnyis} display experiences' },
  { tibetanScript: 'སྣང་སྟོང', wileyScript: 'snang stong', englishTransliteration: 'nang tong', englishTranslation: 'appearance and emptiness, both visible and empty, what appears is open, they appear but are empty, vision and emptiness, simultaneity of appearance and emptiness, empty appearance, perceived emptiness, perceiving emptiness, empty perception' },
  { tibetanScript: 'སྣང་སྟོང་དབྱེར་མེད', wileyScript: 'snang stong dbyer med', englishTransliteration: 'nang tong dbyer med', englishTranslation: 'indivisible experience and emptiness. inseparability of appearance and emptiness' },
  { tibetanScript: 'སྣང་སྟོང་ཟུང་འཇུག་འབུ་མ་ཆེན་པོ', wileyScript: 'snang stong zung \'jug \'bu ma chen po', englishTransliteration: 'nang tong zung \'jug \'buma chenpo', englishTranslation: 'the great Middle Way of the unity of appearance and emptiness' },
  { tibetanScript: 'སྣང་སྟོང་ཟུང་དུ་འཇུག་པའི་རིག་པ', wileyScript: 'snang stong zung du \'jug pa\'i rig pa', englishTransliteration: 'nang tong zung du \'jugpai rigpa', englishTranslation: 'the awareness in which appearances and voidness are inseparably united' },
  { tibetanScript: 'སྣང་དངས', wileyScript: 'snang dangs', englishTransliteration: 'nang dang', englishTranslation: 'naturally clear' },
  { tibetanScript: 'སྣང་བ་སྒྱུ་མ', wileyScript: 'snang ba sgyu ma', englishTransliteration: 'nangwa gyuma', englishTranslation: 'all dharmas appearing natureless like dream and illusion' },
  { tibetanScript: 'སྣང་བ་ཅོག་བཞག', wileyScript: 'snang ba cog bzhag', englishTransliteration: 'nangwa cog bzhag', englishTranslation: '1 of cog bzhag, state of relaxation of the vision (visions of phenomenal reality are recognized in a state of presence and clarity beyond dualistic judgement)' },
  { tibetanScript: 'སྣང་བ་ཆོས་སུ་འགྱུར', wileyScript: 'snang ba chos su \'gyur', englishTransliteration: 'nangwa cho su \'gyur', englishTranslation: 'appearance transformed into dharma' },
  { tibetanScript: 'སྣང་བ་མཆེད་པའི་ཡེ་ཤེས', wileyScript: 'snang ba mched pa\'i ye shes', englishTransliteration: 'nangwa mchedpai yeshe', englishTranslation: 'the wisdom of increased appearance' },
  { tibetanScript: 'སྣང་བ་ཉིད་སྣང་བས་གྲོལ', wileyScript: 'snang ba nyid snang bas grol', englishTransliteration: 'nangwa nyid nangwas drol', englishTranslation: 'the vision itself is self liberated by means of the vision' },
  { tibetanScript: 'སྣང་བ་སྟོང་པ', wileyScript: 'snang ba stong pa', englishTransliteration: 'nangwa tongpa', englishTranslation: 'appearance empty, visible emptiness, manifest emptiness [ry]' },
  { tibetanScript: 'སྣང་བ་སྟོང་པའི་འོད་གསལ', wileyScript: 'snang ba stong pa\'i \'od gsal', englishTransliteration: 'nangwa tongpai odsal', englishTranslation: 'the empty luminosity of appearance' },
  { tibetanScript: 'སྣང་བ་མཐོ་ལིང་ངེ་འབྲེང', wileyScript: 'snang ba mtho ling nge \'breng', englishTransliteration: 'nangwa mtho ling nge \'breng', englishTranslation: 'let one\'s heart soar high and happy' },
  { tibetanScript: 'སྣང་བ་དག་པ', wileyScript: 'snang ba dag pa', englishTransliteration: 'nangwa dagpa', englishTranslation: 'pure appearance free from faults, sacred outlook' },
  { tibetanScript: 'སྣང་བ་དཔེ་ཆར་འཆར་བ', wileyScript: 'snang ba dpe char \'char ba', englishTransliteration: 'nangwa dpe char charba', englishTranslation: 'the phenomenal world will arise as teachings' },
  { tibetanScript: 'སྣང་བ་བན་བུན', wileyScript: 'snang ba ban bun', englishTransliteration: 'nangwaban bun', englishTranslation: 'flickering / fluttering appearances' },
  { tibetanScript: 'སྣང་བ་འོད་ལྡན', wileyScript: 'snang ba \'od ldan', englishTransliteration: 'nangwa od dan', englishTranslation: 'Luminous Vision' },
  { tibetanScript: 'སྣང་བ་སེམས་ལ་ཐིམ་པ', wileyScript: 'snang ba sems la thim pa', englishTransliteration: 'nangwa sem la thimpa', englishTranslation: 'appearances dissolving into mind' },
  { tibetanScript: 'སྣང་བ་སེམས་སུ་ཤར་བ', wileyScript: 'snang ba sems su shar ba', englishTransliteration: 'nangwa sem su sharba', englishTranslation: 'phenomena dawn as your mind' },
  { tibetanScript: 'སྣང་བ་གསལ', wileyScript: 'snang ba gsal', englishTransliteration: 'nangwa sal', englishTranslation: 'luminosity' },
  { tibetanScript: 'སྣང་བ་ལྷན་སྐྱེས་ཆོས་སྐུའི་འོད', wileyScript: 'snang ba lhan skyes chos sku\'i \'od', englishTransliteration: 'nangwa lhan kye choku od', englishTranslation: 'coemergent appearance is the light of dharmakaya' },
  { tibetanScript: 'སྣང་བའི་འོད་གསལ', wileyScript: 'snang ba\'i \'od gsal', englishTransliteration: 'nangwai odsal', englishTranslation: '1) luminous manifestations, manifestations of light; 2) luminosity of appearance' },
  { tibetanScript: 'སྣང་བའི་ཡེ་ཤེས', wileyScript: 'snang ba\'i ye shes', englishTransliteration: 'nangwai yeshe', englishTranslation: 'light of primordial wisdom, manifesting primordial wisdom' },
  { tibetanScript: 'སྣང་ལ་རང་བཞིན་མེད་པ', wileyScript: 'snang la rang bzhin med pa', englishTransliteration: 'nang la rangshin medpa', englishTranslation: 'an appearance without substance, visible yet inconcrete, appearing while having no self nature, apparent though nothing as such, in itself, appearing while nothing in itself' },
  { tibetanScript: 'སྣང་ལ་རང་བཞིན་མེད་པ་ནམ་མཁར་འཇའ་ཚོན་ཤར་བ་ལྟ་བུ', wileyScript: 'snang la rang bzhin med pa nam mkhar \'ja\' tshon shar ba lta bu', englishTransliteration: 'nang la rangshin medpa nam khar ja tshon sharba ta bu', englishTranslation: 'visible but insubstantial, like a rainbow shining in the sky' },
  { tibetanScript: 'སྣང་སེམས་གཉིས་མེད', wileyScript: 'snang sems gnyis med', englishTransliteration: 'nang sem nyi med', englishTranslation: 'non duality of appearances and mind' },
  { tibetanScript: 'སྣང་སྲིད', wileyScript: 'snang srid', englishTransliteration: 'nang srid', englishTranslation: 'all that appears and exists, (entire) world of all possible phenomena(l appearances), appearance and existence, apparent existence phenomena' },
  { tibetanScript: 'སྣང་སྲིད་ཐམས་ཅད', wileyScript: 'snang srid thams cad', englishTransliteration: 'nang srid tham chad', englishTranslation: 'all phenomena of the animate and inanimate universe' },
  { tibetanScript: 'སྣང་གསལ', wileyScript: 'snang gsal', englishTransliteration: 'nangsal', englishTranslation: 'to illuminate; illuminating' },
  { tibetanScript: 'སྟོང་པ།', wileyScript: 'stong pa', englishTransliteration: 'tongpa', englishTranslation: 'sunya, nothing, void, nothing in itself, empty, blank, open, dimensional, hollow, clear, barren, without substance, negation, bare, devoid, vacant, vacuous, vacuum, empty, emptiness, empty state' },
  { tibetanScript: 'སྟོང་བསྒོམ', wileyScript: 'stong bsgom', englishTransliteration: 'tong gom', englishTranslation: 'meditation on emptiness' },
  { tibetanScript: 'འཇའ་ལུས་འཕོ་བ་ཆེན་པོ', wileyScript: '\'ja\' lus \'pho ba chen po', englishTransliteration: 'jalu phoba chenpo', englishTranslation: 'great transference rainbow body' },
  { tibetanScript: 'འཇའ', wileyScript: '\'ja\'', englishTransliteration: 'ja', englishTranslation: 'rainbow, colors of the rainbow' },
  { tibetanScript: 'འཇའ་གུར', wileyScript: '\'ja\' gur', englishTransliteration: 'ja gur', englishTranslation: 'tent of rainbow light' },
  { tibetanScript: 'འཇའ་གུར་ཕུབ', wileyScript: '\'ja\' gur phub', englishTransliteration: 'ja gur phub', englishTranslation: 'a rainbow appeared' },
  { tibetanScript: 'འཇའ་སྤྲིན', wileyScript: '\'ja\' sprin', englishTransliteration: 'ja trin', englishTranslation: 'rainbow hued clouds' },
  { tibetanScript: 'འཇའ་སྤྲིན་གྱི་ཕུང་པོ', wileyScript: '\'ja\' sprin gyi phung po', englishTransliteration: 'ja trin gyi phungpo', englishTranslation: 'masses of rainbow hued clouds' },
  { tibetanScript: 'འཇའ་ཚོན་ལྟ་བུ', wileyScript: '\'ja\' tshon lta bu', englishTransliteration: 'ja tshon ta bu', englishTranslation: 'like a rainbow [ry]' },
  { tibetanScript: 'འཇའ་ཚོན་སྣ་ལྔའི་འོད་ཟེར', wileyScript: '\'ja\' tshon sna lnga\'i \'od zer', englishTransliteration: 'ja tshon na ngai od zer', englishTranslation: 'rays of iridescent light' },
  { tibetanScript: 'འཇའ་ཚོན་འོད་ལྔའི་ཀློང', wileyScript: '\'ja\' tshon \'od lnga\'i klong', englishTransliteration: 'ja tshon od ngai long', englishTranslation: 'space of/ filled with/ dense w rainbow light' },
  { tibetanScript: 'འཇའ་ཚོན་འོད་ལྔའི་ཀློང', wileyScript: '\'ja\' tshon \'od lnga\'i klong', englishTransliteration: 'ja tshon od ngai long', englishTranslation: 'a sphere of five colored rainbow lights' },
  { tibetanScript: 'འཇའ་ཚོན་ཡལ་བ', wileyScript: '\'ja\' tshon yal ba', englishTransliteration: 'ja tshon yalba', englishTranslation: 'vanishing of the rainbow' },
  { tibetanScript: 'འཇའ་ཟེར', wileyScript: '\'ja\' zer', englishTransliteration: 'ja zer', englishTranslation: 'rainbow light' },
  { tibetanScript: 'འཇའ་ཟེར་ཐིག་ལེ་འོད', wileyScript: '\'ja\' zer thig le \'od', englishTransliteration: 'ja zer thigle od', englishTranslation: 'spheres of rainbow light' },
  { tibetanScript: 'འཇའ་འོད་ལྔ་ལྡན་གྱི་ཐིག་ལེ', wileyScript: '\'ja\' \'od lnga ldan gyi thig le', englishTransliteration: 'ja od nga dan gyi thigle', englishTranslation: 'rainbow lights in the form of five colored spheres' },
  { tibetanScript: 'འཇའ་འོད་དྲ་བ', wileyScript: '\'ja\' \'od dra ba', englishTransliteration: 'ja od draba', englishTranslation: 'rainbow light net' },
  { tibetanScript: 'འཇའ་ཡལ་བ་ལྟར', wileyScript: '\'ja\' yal ba ltar', englishTransliteration: 'ja yalba tar', englishTranslation: 'like a disappearing rainbow, disappearing as a rainbow does' },
  { tibetanScript: 'འཇའ་རིས', wileyScript: '\'ja\' ris', englishTransliteration: 'ja ri', englishTranslation: 'rainbow, patterns, designs' },
  { tibetanScript: 'འཇའ་ལུས', wileyScript: '\'ja\' lus', englishTransliteration: 'jalu', englishTranslation: 'rainbow body, authentic existence, transfigured psycho organism, body of a saint vanishing in the rainbow or in the manner of the colors of the rainbow, rainbow body of light' },
  { tibetanScript: 'འཇའ་ལུས་སྒྱུ་མ', wileyScript: '\'ja\' lus sgyu ma', englishTransliteration: 'jalu gyuma', englishTranslation: 'illusory rainbow body' },
  { tibetanScript: 'འཇའ་ལུས་བསྒྲུབ་པ', wileyScript: '\'ja\' lus bsgrub pa', englishTransliteration: 'jalu drubpa', englishTranslation: 'will attain the body of rainbow light' },
  { tibetanScript: 'འཇའ་ལུས་རྡོ་རྗའི་སཀུ', wileyScript: '\'ja\' lus rdo rje\'i sku', englishTransliteration: 'jalu dojeku', englishTranslation: 'rainbow diamond body' },
  { tibetanScript: 'འཇའ་ལུས་འཕ་ཆེན', wileyScript: '\'ja\' lus \'pho chen', englishTransliteration: 'jalu phochen', englishTranslation: 'the great transformation of rainbow body' },
  { tibetanScript: 'འཟའ་ལུས་འདོ་སཀུ', wileyScript: '\'ja\' lus \'od sku', englishTransliteration: 'jalu odku', englishTranslation: 'the body of rainbow light' },
  { tibetanScript: 'སྟོང་པ', wileyScript: 'stong pa', englishTransliteration: 'tongpa', englishTranslation: 'Emptiness, to be devoid of; empty, void, vacant, deserted, clear, hollow, open, without, nothing, blank, negation, openness, void of independent self' },
  { tibetanScript: 'སྟོང་པ་ཆེན་པོ', wileyScript: 'stong pa chen po', englishTransliteration: 'tongpa chenpo', englishTranslation: 'great emptiness, grand / universal emptiness' },
  { tibetanScript: 'སྟོང་པ་ཆེན་པོའི་རྣལ་འབྱོརསྟོང་པ་ཆེན་པོ', wileyScript: 'stong pa chen po\'i rnal \'byor', englishTransliteration: 'tongpa chenpoi nal jor', englishTranslation: 'the yogi of great emptiness' },
  { tibetanScript: 'སྟོང་པ་ཆེན་པོའི་འོད་གསལ', wileyScript: 'stong pa chen po\'i \'od gsal', englishTransliteration: 'tongpa chenpoi odsal', englishTranslation: 'the luminosity of great emptiness' },
  { tibetanScript: 'སྟོང་པ་ཉིད་ཀྱི་ལྟ་བ', wileyScript: 'stong pa nyid kyi lta ba', englishTransliteration: 'tongpa nyid kyi taba', englishTranslation: 'the view [of] emptiness' },
  { tibetanScript: 'སྟོང་པ་ཉིད་ཀྱི་རྣམ་པར་ཐར་པའི་སྒོ', wileyScript: 'stong pa nyid kyi rnam par thar pa\'i sgo', englishTransliteration: 'tongpa nyid kyi nampar tharpai go', englishTranslation: 'the gate of liberation of emptiness' },
  { tibetanScript: 'སྟོང་པ་ཉིད་ཀྱི་ཡེ་ཤེས', wileyScript: 'stong pa nyid kyi ye shes', englishTransliteration: 'tongpa nyid kyi yeshe', englishTranslation: 'Wisdom of emptiness is the dharmadhatu wisdom' },
  { tibetanScript: 'སྟོང་པ་ཉིད་དང་རྟེན་ཅིང་འབྲེལ་བར་འབྱུང་བ', wileyScript: 'stong pa nyid dang rten cing \'brel bar \'byung ba', englishTransliteration: 'tongpa nyid dang ten ching drelbar jungba', englishTranslation: 'emptiness and interdependent arising' },
  { tibetanScript: 'སྟོང་པ་ཉིད་གཟུགས་སོ', wileyScript: 'stong pa nyid gzugs so', englishTransliteration: 'tongpa nyid zug so', englishTranslation: 'emptiness is form' },
  { tibetanScript: 'སྟོང་བསྒོམ།', wileyScript: 'stong bsgom', englishTransliteration: 'tong gom', englishTranslation: 'meditation on emptiness' },
  { tibetanScript: 'སྟོང་པ་རང་གྲོལ', wileyScript: 'stong pa rang grol', englishTransliteration: 'tongpa rangdrol', englishTranslation: 'self liberated emptiness' },
  { tibetanScript: 'སྟོང་པའི་ཆོ་འཕྲུལ', wileyScript: 'stong pa\'i cho \'phrul', englishTransliteration: 'tongpai cho trul', englishTranslation: 'magic of emptiness' },
  { tibetanScript: 'སྟོང་པའི་ཆོས་སྐུ', wileyScript: 'stong pa\'i chos sku', englishTransliteration: 'tongpai choku', englishTranslation: 'empty dharmakaya' },
  { tibetanScript: 'སྟོང་པའི་འོད་གསལ', wileyScript: 'stong pa\'i \'od gsal', englishTransliteration: 'tongpai odsal', englishTranslation: 'empty luminosity; the luminosity of emptiness' },
  { tibetanScript: 'སྟོང་པ', wileyScript: 'stong pa\'i rang rtsal', englishTransliteration: 'tongpai rang tsal', englishTranslation: 'natural expression of emptiness' },
  { tibetanScript: 'སྟོང་པའི་ལྷ', wileyScript: 'stong pa\'i lha', englishTransliteration: 'tongpai lha', englishTranslation: 'deity of emptiness' },
  { tibetanScript: 'བོད་སཀད།', wileyScript: 'bod skad', englishTransliteration: 'bod kad', englishTranslation: 'Tibetan language' },
  { tibetanScript: 'བོད་སཀད་སྒྱུ་འདྲྭ་བ', wileyScript: 'sgyu \'drwa ba', englishTransliteration: 'gyu draba', englishTranslation: 'the magical web' },
  { tibetanScript: 'བོད་སཀད་སྒྱུ་འཕྲུལ', wileyScript: 'sgyu \'phrul', englishTransliteration: 'gyu trul', englishTranslation: 'magical display, magical illusion; maya, illusion, magic, illusory manifestation / creation, miracle, miraculous display' },
  { tibetanScript: 'བོད་སཀད་ལྷུན་ཆགས', wileyScript: 'sgyu chags', englishTransliteration: 'gyu chag', englishTranslation: 'elegant, unchanging, ignified; spontaneously arising; spontaneously arise. sparkling, brilliant' },
  
  // ✨ Add your new terms here - they will automatically get sequential IDs:
  { tibetanScript: 'ནམ་མཁའ', wileyScript: 'nam mkha\'', englishTransliteration: 'namkha', englishTranslation: 'sky, space, the openness of awareness' },
  { tibetanScript: 'ཐབས་ཤེས', wileyScript: 'thabs shes', englishTransliteration: 'thab she', englishTranslation: 'skillful means and wisdom united' },
];
